# Generated by Django 3.1.4 on 2021-01-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('instruction', models.TextField(blank=True, null=True)),
                ('question', models.FileField(null=True, upload_to='question/')),
                ('Class', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('J.S.C', 'J.S.C'), ('S.S.C', 'S.S.C'), ('H.S.C 1st', 'H.S.C 1st'), ('H.S.C 2nd', 'H.S.C 2nd')], default='-----', max_length=10, null=True)),
                ('subject', models.CharField(max_length=100)),
                ('chapter', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now=True, db_index=True)),
                ('author', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
