# Generated by Django 3.1.4 on 2021-01-03 16:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.FileField(default=django.utils.timezone.now, upload_to='question/'),
            preserve_default=False,
        ),
    ]
