# Generated by Django 3.1.4 on 2020-12-31 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
        migrations.RemoveField(
            model_name='verification',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='isTeacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='quota',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='specialist',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Address',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Class',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('J.S.C', 'J.S.C'), ('S.S.C', 'S.S.C'), ('H.S.C 1st', 'H.S.C 1st'), ('H.S.C 2nd', 'H.S.C 2nd')], default='-----', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ContactNumber',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ProfilePicture',
            field=models.ImageField(default='profilePicture/default.jpg', null=True, upload_to='user/'),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.DeleteModel(
            name='Verification',
        ),
    ]
