# Generated by Django 3.1.4 on 2020-12-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201231_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='Active',
            field=models.BooleanField(default=False),
        ),
    ]
